// Generated by CoffeeScript 1.12.4
var encodeArray, encodeObject, encodePair, isObject, pairs;

isObject = require("isObject");

pairs = [];

module.exports = function(values) {
  var key, str;
  for (key in values) {
    encodePair(key, values[key]);
  }
  str = pairs.join("&");
  pairs.length = 0;
  return str;
};

encodePair = function(key, value) {
  if (value === void 0) {
    return;
  }
  if (isObject(value)) {
    encodeObject(value, key);
    return;
  }
  if (Array.isArray(value)) {
    encodeArray(value, key);
    return;
  }
  pairs.push(encodeURIComponent(key) + "=" + encodeURIComponent(value));
};

encodeObject = function(values, parent) {
  var key;
  for (key in values) {
    encodePair(parent + "[" + key + "]", values[key]);
  }
};

encodeArray = function(values, parent) {
  var index;
  index = -1;
  while (++index < values.length) {
    encodePair(parent + "[" + index + "]", values[index]);
  }
};
