// Generated by CoffeeScript 1.12.4
var decode, encode;

encode = require("./encode");

decode = require("./decode");

module.exports = function(value) {
  if (typeof value === "string") {
    if (value) {
      return decode(value);
    } else {
      return {};
    }
  } else {
    return encode(value);
  }
};
