// Generated by CoffeeScript 1.12.4
var decode, encode;

encode = require("./encode");

decode = require("./decode");

module.exports = function(value) {
  if (typeof value === "string") {
    return decode(value);
  } else {
    return encode(value);
  }
};
